const instruments = [
  { name: "agogo1", path: "/samples/brazilian-percussion/agogo1.wav" },
  { name: "agogo2", path: "/samples/brazilian-percussion/agogo2.wav" },
  { name: "caxixi", path: "/samples/brazilian-percussion/caxixi.wav" },
  { name: "kick1", path: "/samples/brazilian-percussion/kick1.wav" },
  { name: "snare", path: "/samples/brazilian-percussion/snare.wav" },
  { name: "surdo1", path: "/samples/brazilian-percussion/surdo1.wav" },
  { name: "surdo2", path: "/samples/brazilian-percussion/surdo2.wav" },
  { name: "surdo3", path: "/samples/brazilian-percussion/surdo3.wav" },
  { name: "surdo4", path: "/samples/brazilian-percussion/surdo4.wav" },
  { name: "tamborim1", path: "/samples/brazilian-percussion/tamborim1.wav" },
  { name: "tamborim2", path: "/samples/brazilian-percussion/tamborim2.wav" },
  { name: "block1", path: "/samples/latin-percussion/block1.wav" },
  { name: "block2", path: "/samples/latin-percussion/block2.wav" },
  { name: "conga1", path: "/samples/latin-percussion/conga1.wav" },
  { name: "conga2", path: "/samples/latin-percussion/conga2.wav" },
  { name: "conga3", path: "/samples/latin-percussion/conga3.wav" },
  { name: "conga4", path: "/samples/latin-percussion/conga4.wav" },
  { name: "cowbell", path: "/samples/latin-percussion/cowbell.wav" },
  { name: "egg1", path: "/samples/latin-percussion/egg1.wav" },
  { name: "egg2", path: "/samples/latin-percussion/egg2.wav" },
  { name: "xequere1", path: "/samples/latin-percussion/xequere1.wav" },
  { name: "xequere2", path: "/samples/latin-percussion/xequere2.wav" },
  { name: "eclap", path: "/samples/eletronic-drums/eclap.wav" },
  { name: "ehat", path: "/samples/eletronic-drums/ehat.wav" },
  { name: "ekick1", path: "/samples/eletronic-drums/ekick1.wav" },
  { name: "ekik2", path: "/samples/eletronic-drums/ekik2.wav" },
  { name: "ekik3", path: "/samples/eletronic-drums/ekik3.wav" },
  { name: "esnare", path: "/samples/eletronic-drums/esnare.wav" },
  { name: "bass", path: "/samples/bass.wav" },
  { name: "block", path: "/samples/block.wav" },
  { name: "bumbo", path: "/samples/bumbo.wav" },
  { name: "claves", path: "/samples/claves.wav" },
  { name: "cymbal", path: "/samples/cymbal.wav" },
  { name: "djembe1", path: "/samples/djembe1.wav" },
  { name: "djembe2", path: "/samples/djembe2.wav" },
  { name: "djembe3", path: "/samples/djembe3.wav" },
  { name: "hit", path: "/samples/hit.wav" },
  { name: "hithat", path: "/samples/hithat.wav" },
  { name: "kick2", path: "/samples/kick2.wav" },
  { name: "kicklow", path: "/samples/kicklow.wav" },
  { name: "tamborim", path: "/samples/tamborim.wav" },
  { name: "berimbau1", path: "/samples/berimbau1.wav" },
  { name: "berimbau2", path: "/samples/berimbau2.wav" },
  { name: "berimbau3", path: "/samples/berimbau3.wav" },
] as const;

type Instruments = (typeof instruments)[number];

export type { Instruments };
export { instruments };
